<div class="container pb-5">
	<h1 class="mb-3 mt-3">VGSpy</h1>
	<hr class="mb-4">

	<div class="row">
		<div class="col-lg-3">
			<div class="sidebar position-sticky" style="top: 10px">
				<ul class="list flex-column" data-vgspy >
					<li><a href="/#linkFirstBlock">Первый блок</a></li>
					<li><a href="/#linkSecondBlock">Второй блок</a></li>
					<li><a href="/#linkThirdBlock">Третий блок</a></li>
					<li><a href="/#linkFourthBlock">Четвертый блок</a></li>
					<li><a href="/#linkFifthBlock">Пятый блок</a></li>
					<li><a href="/#linkSixthBlock">Шестой блок</a></li>
				</ul>
			</div>
		</div>
		<div class="col-lg-9">
			<h3 class="mb-5">Как это работает</h3>
			
			<div class="block" id="linkFirstBlock">
				<h4>Первый блок</h4>
				
				<p><a>Lorem ipsum dolor sit amet</a>, consectetur adipiscing elit. Nunc lorem magna, mattis id pharetra in, accumsan a sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id gravida lacus. Nullam auctor nisl justo, quis eleifend neque molestie id. Aliquam rhoncus nisl sed eros hendrerit viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ac egestas ipsum, sit amet commodo orci. Quisque fermentum ante nulla, id hendrerit elit scelerisque ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
				<p>Nunc id laoreet dolor. Sed porta urna vestibulum tincidunt vehicula. Nulla arcu lorem, dictum nec dapibus pulvinar, lobortis non est. Pellentesque ut semper erat, vitae tempor augue. Aenean eu congue enim, sit amet hendrerit tortor. In tincidunt enim pretium sapien porttitor, eu fermentum turpis vulputate. Phasellus et condimentum nunc. Suspendisse nec quam ut sem dignissim pellentesque efficitur vitae metus. Ut orci justo, dignissim a feugiat ut, ultricies eu tortor. Sed eget sapien id massa imperdiet pulvinar. Praesent malesuada leo ligula, et pharetra urna posuere nec. Curabitur et pharetra est. Ut risus odio, euismod eu sollicitudin at, luctus sed mauris.</p>
				<p>Maecenas efficitur rutrum arcu sit amet dignissim. Aliquam erat volutpat. Nulla feugiat massa sit amet leo scelerisque, pellentesque rhoncus nunc suscipit. Mauris malesuada rutrum tortor eget convallis. Pellentesque turpis ipsum, dapibus non velit in, varius venenatis quam. Vestibulum congue malesuada ipsum quis sodales. Aliquam nec nisl pellentesque, dignissim elit vel, lobortis dui. Pellentesque eleifend bibendum diam, eget accumsan neque bibendum eget. In bibendum nunc vitae ex bibendum interdum. Cras aliquet auctor tellus, eget malesuada enim interdum ut. Mauris tincidunt volutpat lacus nec dapibus. Etiam ut cursus augue. Duis convallis auctor nibh vitae placerat.</p>
				<p>Nulla faucibus commodo convallis. Nam pretium dictum porttitor. Proin urna ex, tristique vitae placerat quis, scelerisque ac massa. Etiam in velit dolor. Nullam quis sodales justo, vitae pulvinar augue. Aliquam et malesuada eros. Phasellus molestie ultrices placerat. Donec eu diam et ipsum volutpat congue. Ut non lectus neque. Proin eu neque hendrerit, lacinia sem et, tristique felis. In hac habitasse platea dictumst. Duis ante mi, ullamcorper eu mollis vel, hendrerit euismod odio. Quisque gravida enim hendrerit dignissim pellentesque. Pellentesque nec facilisis elit. Donec dictum, odio ut dignissim auctor, nisi urna dictum lacus, nec euismod orci sapien bibendum elit. Etiam accumsan vehicula tincidunt.</p>
				<p>Proin lacinia odio convallis lorem commodo, nec iaculis urna volutpat. Mauris ultrices non orci vitae elementum. Proin quam sem, placerat eget pretium vitae, accumsan iaculis urna. Aliquam erat volutpat. Nam quis efficitur risus. Phasellus vehicula vulputate facilisis. Suspendisse sed lorem vitae turpis pretium iaculis. Morbi tincidunt risus nisl, at tristique mi finibus in. Praesent sit amet nunc libero. Aenean maximus ipsum nec malesuada tincidunt. Proin sit amet massa vulputate, blandit erat ac, egestas odio. Mauris vitae mauris eu diam eleifend gravida. Maecenas ullamcorper mollis malesuada.</p>
			</div>
			
			<div class="block" id="linkSecondBlock">
				<h4>Второй блок</h4>
				
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lorem magna, mattis id pharetra in, accumsan a sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id gravida lacus. Nullam auctor nisl justo, quis eleifend neque molestie id. Aliquam rhoncus nisl sed eros hendrerit viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ac egestas ipsum, sit amet commodo orci. Quisque fermentum ante nulla, id hendrerit elit scelerisque ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
				<p>Nunc id laoreet dolor. Sed porta urna vestibulum tincidunt vehicula. Nulla arcu lorem, dictum nec dapibus pulvinar, lobortis non est. Pellentesque ut semper erat, vitae tempor augue. Aenean eu congue enim, sit amet hendrerit tortor. In tincidunt enim pretium sapien porttitor, eu fermentum turpis vulputate. Phasellus et condimentum nunc. Suspendisse nec quam ut sem dignissim pellentesque efficitur vitae metus. Ut orci justo, dignissim a feugiat ut, ultricies eu tortor. Sed eget sapien id massa imperdiet pulvinar. Praesent malesuada leo ligula, et pharetra urna posuere nec. Curabitur et pharetra est. Ut risus odio, euismod eu sollicitudin at, luctus sed mauris.</p>
				<p>Maecenas efficitur rutrum arcu sit amet dignissim. Aliquam erat volutpat. Nulla feugiat massa sit amet leo scelerisque, pellentesque rhoncus nunc suscipit. Mauris malesuada rutrum tortor eget convallis. Pellentesque turpis ipsum, dapibus non velit in, varius venenatis quam. Vestibulum congue malesuada ipsum quis sodales. Aliquam nec nisl pellentesque, dignissim elit vel, lobortis dui. Pellentesque eleifend bibendum diam, eget accumsan neque bibendum eget. In bibendum nunc vitae ex bibendum interdum. Cras aliquet auctor tellus, eget malesuada enim interdum ut. Mauris tincidunt volutpat lacus nec dapibus. Etiam ut cursus augue. Duis convallis auctor nibh vitae placerat.</p>
				<p>Nulla faucibus commodo convallis. Nam pretium dictum porttitor. Proin urna ex, tristique vitae placerat quis, scelerisque ac massa. Etiam in velit dolor. Nullam quis sodales justo, vitae pulvinar augue. Aliquam et malesuada eros. Phasellus molestie ultrices placerat. Donec eu diam et ipsum volutpat congue. Ut non lectus neque. Proin eu neque hendrerit, lacinia sem et, tristique felis. In hac habitasse platea dictumst. Duis ante mi, ullamcorper eu mollis vel, hendrerit euismod odio. Quisque gravida enim hendrerit dignissim pellentesque. Pellentesque nec facilisis elit. Donec dictum, odio ut dignissim auctor, nisi urna dictum lacus, nec euismod orci sapien bibendum elit. Etiam accumsan vehicula tincidunt.</p>
				<p>Proin lacinia odio convallis lorem commodo, nec iaculis urna volutpat. Mauris ultrices non orci vitae elementum. Proin quam sem, placerat eget pretium vitae, accumsan iaculis urna. Aliquam erat volutpat. Nam quis efficitur risus. Phasellus vehicula vulputate facilisis. Suspendisse sed lorem vitae turpis pretium iaculis. Morbi tincidunt risus nisl, at tristique mi finibus in. Praesent sit amet nunc libero. Aenean maximus ipsum nec malesuada tincidunt. Proin sit amet massa vulputate, blandit erat ac, egestas odio. Mauris vitae mauris eu diam eleifend gravida. Maecenas ullamcorper mollis malesuada.</p>
			</div>
			
			<div class="block" id="linkThirdBlock">
				<h4>Третий блок</h4>
				
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lorem magna, mattis id pharetra in, accumsan a sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id gravida lacus. Nullam auctor nisl justo, quis eleifend neque molestie id. Aliquam rhoncus nisl sed eros hendrerit viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ac egestas ipsum, sit amet commodo orci. Quisque fermentum ante nulla, id hendrerit elit scelerisque ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
				<p>Nunc id laoreet dolor. Sed porta urna vestibulum tincidunt vehicula. Nulla arcu lorem, dictum nec dapibus pulvinar, lobortis non est. Pellentesque ut semper erat, vitae tempor augue. Aenean eu congue enim, sit amet hendrerit tortor. In tincidunt enim pretium sapien porttitor, eu fermentum turpis vulputate. Phasellus et condimentum nunc. Suspendisse nec quam ut sem dignissim pellentesque efficitur vitae metus. Ut orci justo, dignissim a feugiat ut, ultricies eu tortor. Sed eget sapien id massa imperdiet pulvinar. Praesent malesuada leo ligula, et pharetra urna posuere nec. Curabitur et pharetra est. Ut risus odio, euismod eu sollicitudin at, luctus sed mauris.</p>
				<p>Maecenas efficitur rutrum arcu sit amet dignissim. Aliquam erat volutpat. Nulla feugiat massa sit amet leo scelerisque, pellentesque rhoncus nunc suscipit. Mauris malesuada rutrum tortor eget convallis. Pellentesque turpis ipsum, dapibus non velit in, varius venenatis quam. Vestibulum congue malesuada ipsum quis sodales. Aliquam nec nisl pellentesque, dignissim elit vel, lobortis dui. Pellentesque eleifend bibendum diam, eget accumsan neque bibendum eget. In bibendum nunc vitae ex bibendum interdum. Cras aliquet auctor tellus, eget malesuada enim interdum ut. Mauris tincidunt volutpat lacus nec dapibus. Etiam ut cursus augue. Duis convallis auctor nibh vitae placerat.</p>
				<p>Nulla faucibus commodo convallis. Nam pretium dictum porttitor. Proin urna ex, tristique vitae placerat quis, scelerisque ac massa. Etiam in velit dolor. Nullam quis sodales justo, vitae pulvinar augue. Aliquam et malesuada eros. Phasellus molestie ultrices placerat. Donec eu diam et ipsum volutpat congue. Ut non lectus neque. Proin eu neque hendrerit, lacinia sem et, tristique felis. In hac habitasse platea dictumst. Duis ante mi, ullamcorper eu mollis vel, hendrerit euismod odio. Quisque gravida enim hendrerit dignissim pellentesque. Pellentesque nec facilisis elit. Donec dictum, odio ut dignissim auctor, nisi urna dictum lacus, nec euismod orci sapien bibendum elit. Etiam accumsan vehicula tincidunt.</p>
				<p>Proin lacinia odio convallis lorem commodo, nec iaculis urna volutpat. Mauris ultrices non orci vitae elementum. Proin quam sem, placerat eget pretium vitae, accumsan iaculis urna. Aliquam erat volutpat. Nam quis efficitur risus. Phasellus vehicula vulputate facilisis. Suspendisse sed lorem vitae turpis pretium iaculis. Morbi tincidunt risus nisl, at tristique mi finibus in. Praesent sit amet nunc libero. Aenean maximus ipsum nec malesuada tincidunt. Proin sit amet massa vulputate, blandit erat ac, egestas odio. Mauris vitae mauris eu diam eleifend gravida. Maecenas ullamcorper mollis malesuada.</p>
			</div>
			
			<div class="block" id="linkFourthBlock">
				<h4>Четвертый блок</h4>
				
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lorem magna, mattis id pharetra in, accumsan a sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id gravida lacus. Nullam auctor nisl justo, quis eleifend neque molestie id. Aliquam rhoncus nisl sed eros hendrerit viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ac egestas ipsum, sit amet commodo orci. Quisque fermentum ante nulla, id hendrerit elit scelerisque ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
				<p>Nunc id laoreet dolor. Sed porta urna vestibulum tincidunt vehicula. Nulla arcu lorem, dictum nec dapibus pulvinar, lobortis non est. Pellentesque ut semper erat, vitae tempor augue. Aenean eu congue enim, sit amet hendrerit tortor. In tincidunt enim pretium sapien porttitor, eu fermentum turpis vulputate. Phasellus et condimentum nunc. Suspendisse nec quam ut sem dignissim pellentesque efficitur vitae metus. Ut orci justo, dignissim a feugiat ut, ultricies eu tortor. Sed eget sapien id massa imperdiet pulvinar. Praesent malesuada leo ligula, et pharetra urna posuere nec. Curabitur et pharetra est. Ut risus odio, euismod eu sollicitudin at, luctus sed mauris.</p>
				<p>Maecenas efficitur rutrum arcu sit amet dignissim. Aliquam erat volutpat. Nulla feugiat massa sit amet leo scelerisque, pellentesque rhoncus nunc suscipit. Mauris malesuada rutrum tortor eget convallis. Pellentesque turpis ipsum, dapibus non velit in, varius venenatis quam. Vestibulum congue malesuada ipsum quis sodales. Aliquam nec nisl pellentesque, dignissim elit vel, lobortis dui. Pellentesque eleifend bibendum diam, eget accumsan neque bibendum eget. In bibendum nunc vitae ex bibendum interdum. Cras aliquet auctor tellus, eget malesuada enim interdum ut. Mauris tincidunt volutpat lacus nec dapibus. Etiam ut cursus augue. Duis convallis auctor nibh vitae placerat.</p>
				<p>Nulla faucibus commodo convallis. Nam pretium dictum porttitor. Proin urna ex, tristique vitae placerat quis, scelerisque ac massa. Etiam in velit dolor. Nullam quis sodales justo, vitae pulvinar augue. Aliquam et malesuada eros. Phasellus molestie ultrices placerat. Donec eu diam et ipsum volutpat congue. Ut non lectus neque. Proin eu neque hendrerit, lacinia sem et, tristique felis. In hac habitasse platea dictumst. Duis ante mi, ullamcorper eu mollis vel, hendrerit euismod odio. Quisque gravida enim hendrerit dignissim pellentesque. Pellentesque nec facilisis elit. Donec dictum, odio ut dignissim auctor, nisi urna dictum lacus, nec euismod orci sapien bibendum elit. Etiam accumsan vehicula tincidunt.</p>
				<p>Proin lacinia odio convallis lorem commodo, nec iaculis urna volutpat. Mauris ultrices non orci vitae elementum. Proin quam sem, placerat eget pretium vitae, accumsan iaculis urna. Aliquam erat volutpat. Nam quis efficitur risus. Phasellus vehicula vulputate facilisis. Suspendisse sed lorem vitae turpis pretium iaculis. Morbi tincidunt risus nisl, at tristique mi finibus in. Praesent sit amet nunc libero. Aenean maximus ipsum nec malesuada tincidunt. Proin sit amet massa vulputate, blandit erat ac, egestas odio. Mauris vitae mauris eu diam eleifend gravida. Maecenas ullamcorper mollis malesuada.</p>
			</div>
			
			<div class="block" id="linkFifthBlock">
				<h4>Пятый блок</h4>
				
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lorem magna, mattis id pharetra in, accumsan a sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id gravida lacus. Nullam auctor nisl justo, quis eleifend neque molestie id. Aliquam rhoncus nisl sed eros hendrerit viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ac egestas ipsum, sit amet commodo orci. Quisque fermentum ante nulla, id hendrerit elit scelerisque ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
				<p>Nunc id laoreet dolor. Sed porta urna vestibulum tincidunt vehicula. Nulla arcu lorem, dictum nec dapibus pulvinar, lobortis non est. Pellentesque ut semper erat, vitae tempor augue. Aenean eu congue enim, sit amet hendrerit tortor. In tincidunt enim pretium sapien porttitor, eu fermentum turpis vulputate. Phasellus et condimentum nunc. Suspendisse nec quam ut sem dignissim pellentesque efficitur vitae metus. Ut orci justo, dignissim a feugiat ut, ultricies eu tortor. Sed eget sapien id massa imperdiet pulvinar. Praesent malesuada leo ligula, et pharetra urna posuere nec. Curabitur et pharetra est. Ut risus odio, euismod eu sollicitudin at, luctus sed mauris.</p>
				<p>Maecenas efficitur rutrum arcu sit amet dignissim. Aliquam erat volutpat. Nulla feugiat massa sit amet leo scelerisque, pellentesque rhoncus nunc suscipit. Mauris malesuada rutrum tortor eget convallis. Pellentesque turpis ipsum, dapibus non velit in, varius venenatis quam. Vestibulum congue malesuada ipsum quis sodales. Aliquam nec nisl pellentesque, dignissim elit vel, lobortis dui. Pellentesque eleifend bibendum diam, eget accumsan neque bibendum eget. In bibendum nunc vitae ex bibendum interdum. Cras aliquet auctor tellus, eget malesuada enim interdum ut. Mauris tincidunt volutpat lacus nec dapibus. Etiam ut cursus augue. Duis convallis auctor nibh vitae placerat.</p>
				<p>Nulla faucibus commodo convallis. Nam pretium dictum porttitor. Proin urna ex, tristique vitae placerat quis, scelerisque ac massa. Etiam in velit dolor. Nullam quis sodales justo, vitae pulvinar augue. Aliquam et malesuada eros. Phasellus molestie ultrices placerat. Donec eu diam et ipsum volutpat congue. Ut non lectus neque. Proin eu neque hendrerit, lacinia sem et, tristique felis. In hac habitasse platea dictumst. Duis ante mi, ullamcorper eu mollis vel, hendrerit euismod odio. Quisque gravida enim hendrerit dignissim pellentesque. Pellentesque nec facilisis elit. Donec dictum, odio ut dignissim auctor, nisi urna dictum lacus, nec euismod orci sapien bibendum elit. Etiam accumsan vehicula tincidunt.</p>
				<p>Proin lacinia odio convallis lorem commodo, nec iaculis urna volutpat. Mauris ultrices non orci vitae elementum. Proin quam sem, placerat eget pretium vitae, accumsan iaculis urna. Aliquam erat volutpat. Nam quis efficitur risus. Phasellus vehicula vulputate facilisis. Suspendisse sed lorem vitae turpis pretium iaculis. Morbi tincidunt risus nisl, at tristique mi finibus in. Praesent sit amet nunc libero. Aenean maximus ipsum nec malesuada tincidunt. Proin sit amet massa vulputate, blandit erat ac, egestas odio. Mauris vitae mauris eu diam eleifend gravida. Maecenas ullamcorper mollis malesuada.</p>
			</div>
			
			<div class="block" id="linkSixthBlock">
				<h4>Шестой блок</h4>
				
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lorem magna, mattis id pharetra in, accumsan a sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id gravida lacus. Nullam auctor nisl justo, quis eleifend neque molestie id. Aliquam rhoncus nisl sed eros hendrerit viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras ac egestas ipsum, sit amet commodo orci. Quisque fermentum ante nulla, id hendrerit elit scelerisque ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
				<p>Nunc id laoreet dolor. Sed porta urna vestibulum tincidunt vehicula. Nulla arcu lorem, dictum nec dapibus pulvinar, lobortis non est. Pellentesque ut semper erat, vitae tempor augue. Aenean eu congue enim, sit amet hendrerit tortor. In tincidunt enim pretium sapien porttitor, eu fermentum turpis vulputate. Phasellus et condimentum nunc. Suspendisse nec quam ut sem dignissim pellentesque efficitur vitae metus. Ut orci justo, dignissim a feugiat ut, ultricies eu tortor. Sed eget sapien id massa imperdiet pulvinar. Praesent malesuada leo ligula, et pharetra urna posuere nec. Curabitur et pharetra est. Ut risus odio, euismod eu sollicitudin at, luctus sed mauris.</p>
				<p>Maecenas efficitur rutrum arcu sit amet dignissim. Aliquam erat volutpat. Nulla feugiat massa sit amet leo scelerisque, pellentesque rhoncus nunc suscipit. Mauris malesuada rutrum tortor eget convallis. Pellentesque turpis ipsum, dapibus non velit in, varius venenatis quam. Vestibulum congue malesuada ipsum quis sodales. Aliquam nec nisl pellentesque, dignissim elit vel, lobortis dui. Pellentesque eleifend bibendum diam, eget accumsan neque bibendum eget. In bibendum nunc vitae ex bibendum interdum. Cras aliquet auctor tellus, eget malesuada enim interdum ut. Mauris tincidunt volutpat lacus nec dapibus. Etiam ut cursus augue. Duis convallis auctor nibh vitae placerat.</p>
				<p>Nulla faucibus commodo convallis. Nam pretium dictum porttitor. Proin urna ex, tristique vitae placerat quis, scelerisque ac massa. Etiam in velit dolor. Nullam quis sodales justo, vitae pulvinar augue. Aliquam et malesuada eros. Phasellus molestie ultrices placerat. Donec eu diam et ipsum volutpat congue. Ut non lectus neque. Proin eu neque hendrerit, lacinia sem et, tristique felis. In hac habitasse platea dictumst. Duis ante mi, ullamcorper eu mollis vel, hendrerit euismod odio. Quisque gravida enim hendrerit dignissim pellentesque. Pellentesque nec facilisis elit. Donec dictum, odio ut dignissim auctor, nisi urna dictum lacus, nec euismod orci sapien bibendum elit. Etiam accumsan vehicula tincidunt.</p>
				<p>Proin lacinia odio convallis lorem commodo, nec iaculis urna volutpat. Mauris ultrices non orci vitae elementum. Proin quam sem, placerat eget pretium vitae, accumsan iaculis urna. Aliquam erat volutpat. Nam quis efficitur risus. Phasellus vehicula vulputate facilisis. Suspendisse sed lorem vitae turpis pretium iaculis. Morbi tincidunt risus nisl, at tristique mi finibus in. Praesent sit amet nunc libero. Aenean maximus ipsum nec malesuada tincidunt. Proin sit amet massa vulputate, blandit erat ac, egestas odio. Mauris vitae mauris eu diam eleifend gravida. Maecenas ullamcorper mollis malesuada.</p>
			</div>
		</div>
	</div>
	<div style="height: 300px"></div>
</div>

<style>
	.sidebar {
		a.active {
			font-weight: bold;
		}
	}
</style>

<script>
	[... document.querySelectorAll('[data-vgspy]')].forEach(el => {
		new vg.VGSpy(el);
	})
</script>